### ISSUE TITLE
Find a way to quantify lossy compression

### ISSUE THREAD

**Issue by JarnoRFB** [neuroinfo-os/deep-bottleneck#70] opened 2018-06-12 15:23 UTC
Can one factor in the accuracy and the compression ratio.

**Comment by felixmzd** [comment] 2018-10-24 11:58
Possible way to do this is to fit a polynomial (i.e 2nd or 3rd order) along the points in the information plane for a specific layer. The parameters of the polynomial quantify "compression"

**Comment by felixmzd** [comment] 2018-10-24 13:47
I think this is a duplicate of #40

**Closed by felixmzd** 2018-10-24 13:47 UTC
Labels: spike
