### ISSUE TITLE
Plot I(X;last_layer) and test accuracy against epochs for ReLU and tanh

### ISSUE THREAD

**Issue by lukeeffenberger** [neuroinfo-os/deep-bottleneck#76] opened 2018-06-19 16:47 UTC

**Comment by lukeeffenberger** [comment] 2018-06-19 16:57
first we need to implement that the reporter saves the validation accuracy

**Comment by felixmzd** [comment] 2018-10-24 13:50
the reporter now saves the validation accuracy

**Comment by felixmzd** [comment] 2018-11-07 15:32
duplicate of #163

**Closed by felixmzd** 2018-11-07 15:32 UTC
